// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendasAPI.Context;

#nullable disable

namespace VendasAPI.Migrations
{
    [DbContext(typeof(VendasAPIContext))]
    [Migration("20260220135202_'TesteInicial'")]
    partial class TesteInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VendasAPI.Model.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Cupons");
                });

            modelBuilder.Entity("VendasAPI.Model.FormaEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorMinimoDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("FormasEntrega");
                });

            modelBuilder.Entity("VendasAPI.Model.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceitaTroco")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FormasPagamento");
                });

            modelBuilder.Entity("VendasAPI.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Estoque")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorPromocao")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("VendasAPI.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeUsuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VendasAPI.Model.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("ContinuarCompra")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CupomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraVenda")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EntregaId")
                        .HasColumnType("int");

                    b.Property<bool>("FinalizarCompra")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NroNotaFiscal")
                        .HasColumnType("int");

                    b.Property<int>("PontosFidelidadeCompra")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoRestante")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalItens")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorEntrega")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorTotalVenda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorTroco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("VendaFinalizada")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CupomId");

                    b.HasIndex("EntregaId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("VendasAPI.Model.VendaFormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("VendaId");

                    b.ToTable("VendaFormaPagamento");
                });

            modelBuilder.Entity("VendasAPI.Model.VendaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("VendaProduto");
                });

            modelBuilder.Entity("VendasAPI.Model.Cliente", b =>
                {
                    b.HasBaseType("VendasAPI.Model.Usuario");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PontosFidelidade")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoAdiantamento")
                        .HasColumnType("decimal(65,30)");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("VendasAPI.Model.Funcionario", b =>
                {
                    b.HasBaseType("VendasAPI.Model.Usuario");

                    b.Property<bool>("PodeAtualizarCadastroCliente")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PodeEditarCupons")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PodeEditarFormasEntrega")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PodeEditarFormasPagamento")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PodeEditarFuncionarios")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PodeEditarProdutos")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue("Funcionario");
                });

            modelBuilder.Entity("VendasAPI.Model.PessoaFisica", b =>
                {
                    b.HasBaseType("VendasAPI.Model.Cliente");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("PessoaFisica");
                });

            modelBuilder.Entity("VendasAPI.Model.PessoaJuridica", b =>
                {
                    b.HasBaseType("VendasAPI.Model.Cliente");

                    b.Property<string>("Cnpj")
                        .HasColumnType("longtext");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("longtext");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("PessoaJuridica");
                });

            modelBuilder.Entity("VendasAPI.Model.Venda", b =>
                {
                    b.HasOne("VendasAPI.Model.Cliente", "Cliente")
                        .WithMany("Compras")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendasAPI.Model.Cupom", "CupomUtilizado")
                        .WithMany()
                        .HasForeignKey("CupomId");

                    b.HasOne("VendasAPI.Model.FormaEntrega", "Entrega")
                        .WithMany()
                        .HasForeignKey("EntregaId");

                    b.Navigation("Cliente");

                    b.Navigation("CupomUtilizado");

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("VendasAPI.Model.VendaFormaPagamento", b =>
                {
                    b.HasOne("VendasAPI.Model.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendasAPI.Model.Venda", "Venda")
                        .WithMany("FormasPagamentoSelecionadas")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPagamento");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("VendasAPI.Model.VendaProduto", b =>
                {
                    b.HasOne("VendasAPI.Model.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendasAPI.Model.Venda", "Venda")
                        .WithMany("ProdutosCompra")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("VendasAPI.Model.Venda", b =>
                {
                    b.Navigation("FormasPagamentoSelecionadas");

                    b.Navigation("ProdutosCompra");
                });

            modelBuilder.Entity("VendasAPI.Model.Cliente", b =>
                {
                    b.Navigation("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
